"""Pydantic schemas for authentication and user management."""

from pydantic import BaseModel, EmailStr, Field, ConfigDict
from typing import Optional


# --------------- Auth Schemas ---------------

class LoginRequest(BaseModel):
    """Schema for login endpoint - accepts email and password."""
    email: EmailStr
    password: str


class TokenResponse(BaseModel):
    """Schema returned after successful login."""
    access_token: str
    token_type: str = "bearer"
    requires_password_change: bool = False


class ChangePasswordRequest(BaseModel):
    """Schema for changing password - requires old password for verification."""
    old_password: str
    new_password: str = Field(..., min_length=8)


# --------------- User Management Schemas ---------------

class UserBase(BaseModel):
    """Base user fields shared across schemas."""
    name: str
    email: EmailStr
    bank_id: Optional[int] = None
    role_id: Optional[int] = None


class UserCreate(UserBase):
    """
    Schema for admin creating a new user.
    Password is auto-generated by the backend.
    """
    pass


class UserLocationRead(BaseModel):
    """Minimal location info returned with user data."""
    location_id: int
    name: str


class UserRead(UserBase):
    """Schema for reading user data - returned to frontend."""
    model_config = ConfigDict(from_attributes=True)

    user_id: int
    requires_password_change: bool
    role_name: Optional[str] = None  # Joined from Role table
    locations: list[UserLocationRead] = []  # User's assigned locations


class UserLocationsUpdate(BaseModel):
    """Schema for updating a user's location assignments."""
    location_ids: list[int]


class UserUpdate(BaseModel):
    """Schema for updating user info (excluding password)."""
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    bank_id: Optional[int] = None
    role_id: Optional[int] = None


class TemporaryPasswordResponse(BaseModel):
    """Returned when admin creates a user - shows temp password once."""
    user: UserRead
    temporary_password: str


# --------------- Permission Schemas ---------------

class PermissionInfo(BaseModel):
    """Single permission with metadata."""
    key: str
    name: str
    description: str


class PermissionsListResponse(BaseModel):
    """All available permissions with groupings."""
    permissions: list[PermissionInfo]
    groups: dict[str, list[str]]


class UserPermissionsUpdate(BaseModel):
    """Schema for updating a user's permissions."""
    permissions: list[str]


class UserPermissionsResponse(BaseModel):
    """Schema for returning a user's permissions."""
    user_id: int
    permissions: list[str]
