"""post auth + event logging

Revision ID: 5155110ac501
Revises: e5f6g7h8i9j0
Create Date: 2026-02-25 19:11:53.391079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5155110ac501'
down_revision: Union[str, Sequence[str], None] = 'e5f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF EXISTS so this is safe on fresh databases that never had these objects.
    op.execute("DROP INDEX IF EXISTS ix_user_locations_id")
    op.execute("DROP INDEX IF EXISTS ix_user_locations_location_id")
    op.execute("DROP INDEX IF EXISTS ix_user_locations_user_id")
    op.execute("DROP TABLE IF EXISTS user_locations")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS must_change_password")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_table('user_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name=op.f('user_locations_location_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_locations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_locations_pkey')),
    sa.UniqueConstraint('user_id', 'location_id', name=op.f('uq_user_location'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_locations_user_id'), 'user_locations', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_locations_location_id'), 'user_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_user_locations_id'), 'user_locations', ['id'], unique=False)
    # ### end Alembic commands ###
