"""add from/to location to inventory_movement

Revision ID: 5a4ea0d991d5
Revises: a827eadfefad
Create Date: 2025-11-18 14:54:28.230674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4ea0d991d5'
down_revision: Union[str, Sequence[str], None] = 'a827eadfefad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movement', sa.Column('from_location_id', sa.Integer(), nullable=True))
    op.add_column('inventory_movement', sa.Column('to_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_movement', 'locations', ['from_location_id'], ['location_id'])
    op.create_foreign_key(None, 'inventory_movement', 'locations', ['to_location_id'], ['location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movement', type_='foreignkey')
    op.drop_constraint(None, 'inventory_movement', type_='foreignkey')
    op.drop_column('inventory_movement', 'to_location_id')
    op.drop_column('inventory_movement', 'from_location_id')
    # ### end Alembic commands ###
