"""item createdby/modifiedby

Revision ID: 610418b9171c
Revises: 67d37e3c4d36
Create Date: 2025-11-03 16:35:35.008856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610418b9171c'
down_revision: Union[str, Sequence[str], None] = '67d37e3c4d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'users', ['modified_by'], ['user_id'])
    op.create_foreign_key(None, 'inventory', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'modified_by')
    op.drop_column('inventory', 'created_by')
    # ### end Alembic commands ###
