"""adjust db

Revision ID: 67d37e3c4d36
Revises: 0e76a1916f35
Create Date: 2025-11-03 16:26:12.905348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d37e3c4d36'
down_revision: Union[str, Sequence[str], None] = '0e76a1916f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_banks',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_food_banks_bank_id'), 'food_banks', ['bank_id'], unique=False)
    op.add_column('inventory', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory', 'food_banks', ['bank_id'], ['bank_id'])
    op.add_column('locations', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'locations', 'food_banks', ['bank_id'], ['bank_id'])
    op.add_column('users', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'food_banks', ['bank_id'], ['bank_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'bank_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'notes')
    op.drop_column('locations', 'bank_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'bank_id')
    op.drop_index(op.f('ix_food_banks_bank_id'), table_name='food_banks')
    op.drop_table('food_banks')
    # ### end Alembic commands ###
