"""add user_id to inventory_movement

Revision ID: 6c9d607ea0fc
Revises: f6g7h8i9j0k1
Create Date: 2026-03-10 16:02:10.460372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9d607ea0fc'
down_revision: Union[str, Sequence[str], None] = 'f6g7h8i9j0k1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movement', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_movement', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movement', type_='foreignkey')
    op.drop_column('inventory_movement', 'user_id')
    # ### end Alembic commands ###
