"""add inventory_movement table

Revision ID: a827eadfefad
Revises: merge_9424a675_b1f2c3d
Create Date: 2025-11-18 14:04:30.843550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a827eadfefad'
down_revision: Union[str, Sequence[str], None] = 'merge_9424a675_b1f2c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('OUTBOUND', 'WASTE', 'ADJUSTMENT', 'TRANSFER', name='movementtype'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movement_id'), 'inventory_movement', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_item_id'), 'inventory_movement', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movement_item_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_id'), table_name='inventory_movement')
    op.drop_table('inventory_movement')
    # ### end Alembic commands ###
