"""adding table for demand forecasting (kaggle dataset)

Revision ID: cc0937f373c3
Revises: 9424a6750407
Create Date: 2025-11-17 17:54:22.605084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0937f373c3'
down_revision: Union[str, Sequence[str], None] = '9424a6750407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
